---
title: "lab5"
author: "Stephanie Femrite"
date: "4/13/2020"
output:
  html_document: default
  pdf_document: default
---
```{r}
library(tidyverse)

acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)

per <-read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)

```

Part 1

1)

```{r}
ggplot(acc, aes(x= DAY_WEEK)) + geom_bar()
```

It looks like  more accidents occur on Saturday (day 7) than any other day

2)
```{r}
acc1 <- acc %>%
  filter(HOUR != 99)

ggplot(acc1, aes(x= HOUR)) + geom_bar()
```
The most accidents occur at 6 PM.

3)
```{r}
acc2 <- acc %>%
  group_by(DRUNK_DR) %>%
  filter(DRUNK_DR != 0)

count(acc2)
```
There are 8769 accidents involving drunk drivers.

Part 2

4)
```{r}
unique(per$PER_TYP)
```
5)
```{r}
accPer <- inner_join(acc, per)
```
6)
```{r}
head(accPer)
accPer1 <- accPer %>%
  filter(HOUR != 99)

ggplot(accPer1, aes(x=HOUR, y = SEX))+ geom_point()
```  
7) and 8)
```{r}
library(readxl)

county <- readxl::read_xlsx("FRPP GLC - United StatesFeb132020.xlsx")

map <- map_data("county") %>%
  mutate(`State Name` = region, `County Name` = subregion)


county <- county %>%
  mutate(CITY = as.integer(`City Code`),
         COUNTY = as.integer(`County Code`),
         STATE = as.integer(`State Code`))

acc2 <- acc %>%
  group_by(STATE, COUNTY) %>%
  summarize(count=n())


county <- county %>%
  mutate(`State Name` = tolower(`State Name`),
        `County Name` = tolower(`County Name`))

final <- left_join(map, county, by = c("State Name" = "State Name", "County Name" = "County Name"))

final <- left_join(final, acc2, by = c("STATE" = "STATE", "COUNTY" = "COUNTY"))


final %>%
ggplot(aes(x=long, y=lat, fill = log(count))) + geom_polygon(aes(group=group)) + coord_map()


```

